export default function createFieldsGeneral (){
    const fragment = document.createDocumentFragment();
    const labelVisit = document.createElement('label');
    labelVisit.htmlFor = "visit";
    labelVisit.textContent = "Цель визита";
    labelVisit.className = 'mx-2 mt-2';
    const inputVisit = document.createElement('input');
    inputVisit.id = "visit";
    inputVisit.type = "text";
    inputVisit.placeholder = "Цель визита";
    inputVisit.classList.add("mb-2");
    const labelDescription = document.createElement('label');
    labelDescription.htmlFor = "description";
    labelDescription.textContent = "Краткое описание визита";
    labelDescription.className = 'mx-2';
    const inputDescription = document.createElement('input');
    inputDescription.id = "description";
    inputDescription.type = "text";
    inputDescription.placeholder = "Описание визита";
    inputDescription.classList.add("mb-2");

    const selectUrgency = document.createElement('select');
    selectUrgency.className = "form-select form-select-m mb-2";
    const optionUrgency = document.createElement('option');
    optionUrgency.selected;
    optionUrgency.textContent = "Срочность визита";
    const urgencyHigh = document.createElement('option');
    urgencyHigh.value = '1';
    urgencyHigh.textContent = 'High';
    const urgencyNormal = document.createElement('option');
    urgencyNormal.value = '2';
    urgencyNormal.textContent = 'Normal';
    const urgencyLow = document.createElement('option');
    urgencyLow.value = '3';
    urgencyLow.textContent = 'Low';

    selectUrgency.append(optionUrgency, urgencyHigh, urgencyNormal, urgencyLow);
    const labelName = document.createElement('label');
    labelName.htmlFor = "full-name";
    labelName.textContent = "Фамилия Имя Отчество";
    labelName.className = 'mx-2';
    const inputName = document.createElement('input');
    inputName.id = "full-name";
    inputName.className = "mx-3";
    inputName.type = "text";
    inputName.placeholder = "ФИО";
    inputName.classList.add("mb-2");
    fragment.append(labelVisit, inputVisit, labelDescription, inputDescription, selectUrgency,labelName,inputName);
    return fragment;
}
